#encoding: utf-8
#Aprovados
material = Category.create(name: 'Material', is_visible: true)
[1, 2, 3, 5, 304, 307].each do |id|
  cat = Category.find(id)
  cat.parent = material
  cat.save
end

producao = Category.create(name: 'Produção', is_visible: true, parent_id: 201)
[202, 203].each do |id|
  c = Category.find(id)
  c.parent = producao
  c.save
end

Category.create(name: 'Tecnologia que otimiza o uso da água', parent: producao)
Category.create(name: 'Tratamento do efluente', parent: producao)
Category.create(name: 'Efluente direcionado a outro processo interno', parent: producao)
Category.create(name: 'Efluente tratado direcionado a ciclo natural', parent: producao)
fonte = Category.create(name: 'Fonte', is_visible: true, parent_id: 201)
Category.create(name: 'Substituição do componente água maior que 50% na formulação', parent: fonte)
Category.create(name: 'Substituição do componente água menor que 50% na formulação', parent: fonte)
uso = Category.create(name: 'Uso', is_visible: true, parent_id: 201)
Category.create(name: 'Minimiza o uso de água na aplicação e proporciona economia maior que 50%', parent: uso)
Category.create(name: 'Minimiza o uso de água na aplicação e proporciona economia menor que 50%', parent: uso)

Category.create(name: 'Matéria-prima reciclada na composição maior que 50%', parent_id: 170)
Category.create(name: 'Matéria-prima reutilizada na composição é maior que 50%', parent_id: 170)
Category.create(name: 'Matéria-prima virgem e não renovável na composição é maior que 50%', parent_id: 170)
Category.create(name: 'Matéria-prima virgem e renovável na composição é maior que 50%', parent_id: 170)
Category.create(name: 'Desmontável', parent_id: 170)
Category.create(name: 'Elemento de origem animal na composição é menor que 50% do total', parent_id: 170)
Category.create(name: 'Elemento de origem animal na composição é maior que 50% do total', parent_id: 170)
Category.create(name: 'Embalagem sustentável', parent_id: 170)

Category.create(name: 'Inflamável', parent_id: 182)
Category.create(name: 'Resíduos atóxicos', parent_id: 182)

Category.create(name: 'Desenvolve programa de responsabilidade social', parent_id: 204)
Category.create(name: 'Investimento na capacitação da mão-de-obra', parent_id: 204)
Category.create(name: 'Oferece condições adequadas de saúde e segurança para os trabalhadores', parent_id: 204)
Category.create(name: 'Investimento em melhorias na qualidade de vida dos funcionários', parent_id: 204)
Category.create(name: 'Contribui em melhorias ambientais para o entorno', parent_id: 204)
Category.create(name: 'Possui indicador para monitorar o impacto ambiental', parent_id: 204)

producao_energia = Category.create(name: 'Produção', parent_id: 194)
[195, 196].each do |id|
  c = Category.find(id)
  c.parent = producao_energia
  c.save
end

fonte_energia = Category.create(name: 'Fonte', parent_id: 194)
[197].each do |id|
  c = Category.find(id)
  c.parent = fonte_energia
  c.save
end
Category.create(name: 'Utilização de energia eólica menor que 50%', parent: fonte_energia)
Category.create(name: 'Utilização de energia eólica maior que 50%', parent: fonte_energia)
Category.create(name: 'Utilização de energia hidroelétrica maior que 50%', parent: fonte_energia)
Category.create(name: 'Utilização de energia a partir de biomassa menor que 50%', parent: fonte_energia)
Category.create(name: 'Utilização de energia a partir de biomassa maior que 50%', parent: fonte_energia)
Category.create(name: 'Utilização de energia solar menor que 50%', parent: fonte_energia)
Category.create(name: 'Utilização de energia solar maior que 50%', parent: fonte_energia)

uso_energia = Category.create(name: 'Uso', parent_id: 194)
[198, 199, 200, 297].each do |id|
  c = Category.find(id)
  c.parent = uso_energia
  c.save
end
Category.create(name: 'Contribui para eficiência energética', parent: uso_energia)
Category.create(name: 'Contribui para geração de energia', parent: uso_energia)

certificacao_energia = Category.create(name: 'Certificação', parent_id: 194)
Category.create(name: 'Possui selo ou certificação energética', parent: certificacao_energia)


Category.create(name: 'Possui uma política ambiental', parent_id: 212)
Category.create(name: 'Possui sistema de gestão ambiental', parent_id: 212)
Category.create(name: 'Realiza periodicamente campanhas internas de educação ambiental', parent_id: 212)
Category.create(name: 'Comunicação ativa de suas práticas ambientais com stakeholders', parent_id: 212)
Category.create(name: 'Elabora e divulga balanço social ou relatório de sustentabilidade', parent_id: 212)
Category.create(name: 'Diferencial ambiental do produto é usado como estratégia de marketing', parent_id: 212)
Category.create(name: 'Utiliza princípios de prevenção a poluição', parent_id: 212)
Category.create(name: 'Há a compensação das emissões de carbono', parent_id: 212)
Category.create(name: 'Tecnologia que trata os resíduos no processo produtivo', parent_id: 212)
Category.create(name: 'Uso de tecnologia para a minimização de geração de resíduos', parent_id: 212)
Category.create(name: 'Gestão e monitoramento da logística garantindo qualidade ambiental', parent_id: 212)
Category.create(name: 'Programa de logística reversa', parent_id: 212)
Category.create(name: 'O produto possui selo ambiental', parent_id: 212)
Category.create(name: 'O produto já recebeu prêmio', parent_id: 212)

Category.create(name: 'Fachada', parent_id: 1)

produto = Category.create(name: 'Produto')
sustentabilidade_produto = Category.create(name: 'Sustentabilidade', parent: produto)

agua_produto = Category.create(name: 'Água', parent: sustentabilidade_produto)
producao_produto = Category.create(name: 'Produção', parent: agua_produto)
Category.create(name: 'Reuso na produção', parent: producao_produto)
Category.create(name: 'Uso racional na produção', parent: producao_produto)
Category.create(name: 'Tecnologia que otimiza o uso da água', parent: producao_produto)
Category.create(name: 'Tratamento do efluente', parent: producao_produto)
Category.create(name: 'Efluente direcionado a outro processo interno', parent: producao_produto)
Category.create(name: 'Efluente tratado direcionado a ciclo natural', parent: producao_produto)
fonte_produto = Category.create(name: 'Fonte', is_visible: true, parent: agua_produto)
Category.create(name: 'Substituição do componente água maior que 50% na formulação', parent: fonte_produto)
Category.create(name: 'Substituição do componente água menor que 50% na formulação', parent: fonte_produto)
uso_produto = Category.create(name: 'Uso', is_visible: true, parent: agua_produto)
Category.create(name: 'Minimiza o uso de água na aplicação e proporciona economia maior que 50%', parent: uso_produto)
Category.create(name: 'Minimiza o uso de água na aplicação e proporciona economia menor que 50%', parent: uso_produto)

ciclo_produto = Category.create(name: 'Ciclo', parent: sustentabilidade_produto)
Category.create(name: 'Alta durabilidade', parent: ciclo_produto)
Category.create(name: 'Biodegradável', parent: ciclo_produto)
Category.create(name: 'Compostável', parent: ciclo_produto)
Category.create(name: 'A matéria-prima é proveniente de manejo sustentável', parent: ciclo_produto)
Category.create(name: 'Matéria-prima reciclada na composição menor que 50%', parent: ciclo_produto)
Category.create(name: 'Matéria-prima reciclada na composição maior que 50%', parent: ciclo_produto)
Category.create(name: 'Matéria-prima reutilizada na composição é menor que 50%', parent: ciclo_produto)
Category.create(name: 'Matéria-prima reutilizada na composição é maior que 50%', parent: ciclo_produto)
Category.create(name: 'Matéria-prima virgem e não renovável na composição é menor que 50%', parent: ciclo_produto)
Category.create(name: 'Matéria-prima virgem e não renovável na composição é maior que 50%', parent: ciclo_produto)
Category.create(name: 'Matéria-prima virgem e renovável na composição é menor que 50%', parent: ciclo_produto)
Category.create(name: 'Matéria-prima virgem e renovável na composição é maior que 50%', parent: ciclo_produto)
Category.create(name: 'Reciclável', parent: ciclo_produto)
Category.create(name: 'Reutilizável', parent: ciclo_produto)
Category.create(name: 'Desmontável', parent: ciclo_produto)
Category.create(name: 'Elemento de origem animal na composição é menor que 50% do total', parent: ciclo_produto)
Category.create(name: 'Elemento de origem animal na composição é maior que 50% do total', parent: ciclo_produto)
Category.create(name: 'Embalagem sustentável', parent: ciclo_produto)

seguranca_produto = Category.create(name: 'Segurança', parent: sustentabilidade_produto)
Category.create(name: 'Atóxico durante a produção', parent: seguranca_produto)
Category.create(name: 'Atóxico durante o uso', parent: seguranca_produto)
Category.create(name: 'Baixa emissão de GEE', parent: seguranca_produto)
Category.create(name: 'Baixa emissão de COVs', parent: seguranca_produto)
Category.create(name: 'Destinação adequada de resíduos', parent: seguranca_produto)
Category.create(name: 'Inerte', parent: seguranca_produto)
Category.create(name: 'Inodoro', parent: seguranca_produto)
Category.create(name: 'Minimização da geração de resíduos', parent: seguranca_produto)
Category.create(name: 'Substituição de insumos tóxicos', parent: seguranca_produto)
Category.create(name: 'Inflamável', parent: seguranca_produto)
Category.create(name: 'Resíduos atóxicos', parent: seguranca_produto)

humano_produto = Category.create(name: 'Humano-social', parent: sustentabilidade_produto)
Category.create(name: 'Comercializado sob conceitos de mercado justo', parent: humano_produto)
Category.create(name: 'Gera emprego e renda para comunidade local', parent: humano_produto)
Category.create(name: 'Promove a inclusão social de mulheres, deficientes físicos, jovens e outros', parent: humano_produto)
Category.create(name: 'Produção valoriza cultura e tradição local', parent: humano_produto)
Category.create(name: 'Produção envolve mão-de-obra de cooperativas ou associações', parent: humano_produto)
Category.create(name: 'Seu uso contribui para a acessibilidade', parent: humano_produto)
Category.create(name: 'Contribui para disseminação de práticas sócio-ambientais', parent: humano_produto)
Category.create(name: 'Desenvolve programa de responsabilidade social', parent: humano_produto)
Category.create(name: 'Investimento na capacitação da mão-de-obra', parent: humano_produto)
Category.create(name: 'Oferece condições adequadas de saúde e segurança para os trabalhadores', parent: humano_produto)
Category.create(name: 'Investimento em melhorias na qualidade de vida dos funcionários', parent: humano_produto)
Category.create(name: 'Contribui em melhorias ambientais para o entorno', parent: humano_produto)
Category.create(name: 'Possui indicador para monitorar o impacto ambiental', parent: humano_produto)

energia_produto = Category.create(name: 'Energia', parent: sustentabilidade_produto)
producao_energia_produto = Category.create(name: 'Produção', parent: energia_produto)
Category.create(name: 'Alta eficiência energética da produção', parent: producao_energia_produto)
Category.create(name: 'Baixo consumo de energia', parent: producao_energia_produto)
fonte_energia_produto = Category.create(name: 'Fonte', parent: energia_produto)
Category.create(name: 'Utilização de energia eólica menor que 50%', parent: fonte_energia_produto)
Category.create(name: 'Utilização de energia eólica maior que 50%', parent: fonte_energia_produto)
Category.create(name: 'Utilização de energia hidroelétrica menor que 50%', parent: fonte_energia_produto)
Category.create(name: 'Utilização de energia hidroelétrica maior que 50%', parent: fonte_energia_produto)
Category.create(name: 'Utilização de energia a partir de biomassa menor que 50%', parent: fonte_energia_produto)
Category.create(name: 'Utilização de energia a partir de biomassa maior que 50%', parent: fonte_energia_produto)
Category.create(name: 'Utilização de energia solar menor que 50%', parent: fonte_energia_produto)
Category.create(name: 'Utilização de energia solar maior que 50%', parent: fonte_energia_produto)
uso_energia_produto = Category.create(name: 'Uso', parent: energia_produto)
Category.create(name: 'Promove alta eficiência energética', parent: uso_energia_produto)
Category.create(name: 'Baixo consumo de energia', parent: uso_energia_produto)
Category.create(name: 'Promove o uso de energia renovável', parent: uso_energia_produto)
Category.create(name: 'Contribui para eficiência energética', parent: uso_energia_produto)
Category.create(name: 'Contribui para geração de energia', parent: uso_energia_produto)
Category.create(name: 'Produção prioriza processos manuais', parent: uso_energia_produto)
certificacao_energia_produto = Category.create(name: 'Certificação', parent: energia_produto)
Category.create(name: 'Possui selo ou certificação energética', parent: certificacao_energia_produto)

gestao_produto = Category.create(name: 'Gestão', parent: sustentabilidade_produto)
Category.create(name: 'Boas práticas socioambientais', parent: gestao_produto)
Category.create(name: 'Fornecedores ambientalmente adequados', parent: gestao_produto)
Category.create(name: 'Cadeia produtiva regional', parent: gestao_produto)
Category.create(name: 'Possui uma política ambiental', parent: gestao_produto)
Category.create(name: 'Possui sistema de gestão ambiental', parent: gestao_produto)
Category.create(name: 'Realiza periodicamente campanhas internas de educação ambiental', parent: gestao_produto)
Category.create(name: 'Comunicação ativa de suas práticas ambientais com stakeholders', parent: gestao_produto)
Category.create(name: 'Elabora e divulga balanço social ou relatório de sustentabilidade', parent: gestao_produto)
Category.create(name: 'Diferencial ambiental do produto é usado como estratégia de marketing', parent: gestao_produto)
Category.create(name: 'Utiliza princípios de prevenção a poluição', parent: gestao_produto)
Category.create(name: 'Há a compensação das emissões de carbono', parent: gestao_produto)
Category.create(name: 'Tecnologia que trata os resíduos no processo produtivo', parent: gestao_produto)
Category.create(name: 'Uso de tecnologia para a minimização de geração de resíduos', parent: gestao_produto)
Category.create(name: 'Gestão e monitoramento da logística garantindo qualidade ambiental', parent: gestao_produto)
Category.create(name: 'Programa de logística reversa', parent: gestao_produto)
Category.create(name: 'O produto possui selo ambiental', parent: gestao_produto)
Category.create(name: 'O produto já recebeu prêmio', parent: gestao_produto)

uso_produto = Category.create(name: 'Uso', parent: produto)
Category.create(name: 'Casa e construção', parent: uso_produto)
Category.create(name: 'Esporte e Lazer', parent: uso_produto)
Category.create(name: 'Moda', parent: uso_produto)
Category.create(name: 'Eventos', parent: uso_produto)
Category.create(name: 'Embalagens', parent: uso_produto)

disponibilidade_produto = Category.create(name: 'Disponibilidade', parent: produto)
Category.create(name: 'Disponível para venda', parent: disponibilidade_produto)
Category.create(name: 'Em desenvolvimento', parent: disponibilidade_produto)

local_produto = Category.create(name: 'Local de produção', parent: produto)
Category.create(name: 'Brasil', parent: local_produto)
Category.create(name: 'Fora do Brasil', parent: local_produto)



sistema = Category.create(name: 'Sistema')
sustentabilidade_sistema = Category.create(name: 'Sustentabilidade', parent: sistema)

agua_sistema = Category.create(name: 'Água', parent: sustentabilidade_sistema)
producao_sistema = Category.create(name: 'Produção', parent: agua_sistema)
Category.create(name: 'Reuso na produção', parent: producao_sistema)
Category.create(name: 'Uso racional na produção', parent: producao_sistema)
Category.create(name: 'Tecnologia que otimiza o uso da água', parent: producao_sistema)
Category.create(name: 'Tratamento do efluente', parent: producao_sistema)
Category.create(name: 'Efluente direcionado a outro processo interno', parent: producao_sistema)
Category.create(name: 'Efluente tratado direcionado a ciclo natural', parent: producao_sistema)
fonte_sistema = Category.create(name: 'Fonte', is_visible: true, parent: agua_sistema)
Category.create(name: 'Substituição do componente água maior que 50% na formulação', parent: fonte_sistema)
Category.create(name: 'Substituição do componente água menor que 50% na formulação', parent: fonte_sistema)
uso_sistema = Category.create(name: 'Uso', is_visible: true, parent: agua_sistema)
Category.create(name: 'Minimiza o uso de água na aplicação e proporciona economia maior que 50%', parent: uso_sistema)
Category.create(name: 'Minimiza o uso de água na aplicação e proporciona economia menor que 50%', parent: uso_sistema)

ciclo_sistema = Category.create(name: 'Ciclo', parent: sustentabilidade_sistema)
Category.create(name: 'Alta durabilidade', parent: ciclo_sistema)
Category.create(name: 'Biodegradável', parent: ciclo_sistema)
Category.create(name: 'Compostável', parent: ciclo_sistema)
Category.create(name: 'A matéria-prima é proveniente de manejo sustentável', parent: ciclo_sistema)
Category.create(name: 'Matéria-prima reciclada na composição menor que 50%', parent: ciclo_sistema)
Category.create(name: 'Matéria-prima reciclada na composição maior que 50%', parent: ciclo_sistema)
Category.create(name: 'Matéria-prima reutilizada na composição é menor que 50%', parent: ciclo_sistema)
Category.create(name: 'Matéria-prima reutilizada na composição é maior que 50%', parent: ciclo_sistema)
Category.create(name: 'Matéria-prima virgem e não renovável na composição é menor que 50%', parent: ciclo_sistema)
Category.create(name: 'Matéria-prima virgem e não renovável na composição é maior que 50%', parent: ciclo_sistema)
Category.create(name: 'Matéria-prima virgem e renovável na composição é menor que 50%', parent: ciclo_sistema)
Category.create(name: 'Matéria-prima virgem e renovável na composição é maior que 50%', parent: ciclo_sistema)
Category.create(name: 'Reciclável', parent: ciclo_sistema)
Category.create(name: 'Reutilizável', parent: ciclo_sistema)
Category.create(name: 'Desmontável', parent: ciclo_sistema)
Category.create(name: 'Elemento de origem animal na composição é menor que 50% do total', parent: ciclo_sistema)
Category.create(name: 'Elemento de origem animal na composição é maior que 50% do total', parent: ciclo_sistema)
Category.create(name: 'Embalagem sustentável', parent: ciclo_sistema)

seguranca_sistema = Category.create(name: 'Segurança', parent: sustentabilidade_sistema)
Category.create(name: 'Atóxico durante a produção', parent: seguranca_sistema)
Category.create(name: 'Atóxico durante o uso', parent: seguranca_sistema)
Category.create(name: 'Baixa emissão de GEE', parent: seguranca_sistema)
Category.create(name: 'Baixa emissão de COVs', parent: seguranca_sistema)
Category.create(name: 'Destinação adequada de resíduos', parent: seguranca_sistema)
Category.create(name: 'Inerte', parent: seguranca_sistema)
Category.create(name: 'Inodoro', parent: seguranca_sistema)
Category.create(name: 'Minimização da geração de resíduos', parent: seguranca_sistema)
Category.create(name: 'Substituição de insumos tóxicos', parent: seguranca_sistema)
Category.create(name: 'Inflamável', parent: seguranca_sistema)
Category.create(name: 'Resíduos atóxicos', parent: seguranca_sistema)

humano_sistema = Category.create(name: 'Humano-social', parent: sustentabilidade_sistema)
Category.create(name: 'Comercializado sob conceitos de mercado justo', parent: humano_sistema)
Category.create(name: 'Gera emprego e renda para comunidade local', parent: humano_sistema)
Category.create(name: 'Promove a inclusão social de mulheres, deficientes físicos, jovens e outros', parent: humano_sistema)
Category.create(name: 'Produção valoriza cultura e tradição local', parent: humano_sistema)
Category.create(name: 'Produção envolve mão-de-obra de cooperativas ou associações', parent: humano_sistema)
Category.create(name: 'Seu uso contribui para a acessibilidade', parent: humano_sistema)
Category.create(name: 'Contribui para disseminação de práticas sócio-ambientais', parent: humano_sistema)
Category.create(name: 'Desenvolve programa de responsabilidade social', parent: humano_sistema)
Category.create(name: 'Investimento na capacitação da mão-de-obra', parent: humano_sistema)
Category.create(name: 'Oferece condições adequadas de saúde e segurança para os trabalhadores', parent: humano_sistema)
Category.create(name: 'Investimento em melhorias na qualidade de vida dos funcionários', parent: humano_sistema)
Category.create(name: 'Contribui em melhorias ambientais para o entorno', parent: humano_sistema)
Category.create(name: 'Possui indicador para monitorar o impacto ambiental', parent: humano_sistema)

energia_sistema = Category.create(name: 'Energia', parent: sustentabilidade_sistema)
producao_energia_sistema = Category.create(name: 'Produção', parent: energia_sistema)
Category.create(name: 'Alta eficiência energética da produção', parent: producao_energia_sistema)
Category.create(name: 'Baixo consumo de energia', parent: producao_energia_sistema)
fonte_energia_sistema = Category.create(name: 'Fonte', parent: energia_sistema)
Category.create(name: 'Utilização de energia eólica menor que 50%', parent: fonte_energia_sistema)
Category.create(name: 'Utilização de energia eólica maior que 50%', parent: fonte_energia_sistema)
Category.create(name: 'Utilização de energia hidroelétrica menor que 50%', parent: fonte_energia_sistema)
Category.create(name: 'Utilização de energia hidroelétrica maior que 50%', parent: fonte_energia_sistema)
Category.create(name: 'Utilização de energia a partir de biomassa menor que 50%', parent: fonte_energia_sistema)
Category.create(name: 'Utilização de energia a partir de biomassa maior que 50%', parent: fonte_energia_sistema)
Category.create(name: 'Utilização de energia solar menor que 50%', parent: fonte_energia_sistema)
Category.create(name: 'Utilização de energia solar maior que 50%', parent: fonte_energia_sistema)
uso_energia_sistema = Category.create(name: 'Uso', parent: energia_sistema)
Category.create(name: 'Promove alta eficiência energética', parent: uso_energia_sistema)
Category.create(name: 'Baixo consumo de energia', parent: uso_energia_sistema)
Category.create(name: 'Promove o uso de energia renovável', parent: uso_energia_sistema)
Category.create(name: 'Contribui para eficiência energética', parent: uso_energia_sistema)
Category.create(name: 'Contribui para geração de energia', parent: uso_energia_sistema)
Category.create(name: 'Produção prioriza processos manuais', parent: uso_energia_sistema)
certificacao_energia_sistema = Category.create(name: 'Certificação', parent: energia_sistema)
Category.create(name: 'Possui selo ou certificação energética', parent: certificacao_energia_sistema)

gestao_sistema = Category.create(name: 'Gestão', parent: sustentabilidade_sistema)
Category.create(name: 'Boas práticas socioambientais', parent: gestao_sistema)
Category.create(name: 'Fornecedores ambientalmente adequados', parent: gestao_sistema)
Category.create(name: 'Cadeia produtiva regional', parent: gestao_sistema)
Category.create(name: 'Possui uma política ambiental', parent: gestao_sistema)
Category.create(name: 'Possui sistema de gestão ambiental', parent: gestao_sistema)
Category.create(name: 'Realiza periodicamente campanhas internas de educação ambiental', parent: gestao_sistema)
Category.create(name: 'Comunicação ativa de suas práticas ambientais com stakeholders', parent: gestao_sistema)
Category.create(name: 'Elabora e divulga balanço social ou relatório de sustentabilidade', parent: gestao_sistema)
Category.create(name: 'Diferencial ambiental do produto é usado como estratégia de marketing', parent: gestao_sistema)
Category.create(name: 'Utiliza princípios de prevenção a poluição', parent: gestao_sistema)
Category.create(name: 'Há a compensação das emissões de carbono', parent: gestao_sistema)
Category.create(name: 'Tecnologia que trata os resíduos no processo produtivo', parent: gestao_sistema)
Category.create(name: 'Uso de tecnologia para a minimização de geração de resíduos', parent: gestao_sistema)
Category.create(name: 'Gestão e monitoramento da logística garantindo qualidade ambiental', parent: gestao_sistema)
Category.create(name: 'Programa de logística reversa', parent: gestao_sistema)
Category.create(name: 'O produto possui selo ambiental', parent: gestao_sistema)
Category.create(name: 'O produto já recebeu prêmio', parent: gestao_sistema)

setor_sistema = Category.create(name: 'Setor', parent: sistema)
Category.create(name: 'Energia', parent: setor_sistema)
Category.create(name: 'Água', parent: setor_sistema)
Category.create(name: 'Conforto Ambiental', parent: setor_sistema)
Category.create(name: 'Resíduos', parent: setor_sistema)
Category.create(name: 'Construção', parent: setor_sistema)

disponibilidade_sistema = Category.create(name: 'Disponibilidade', parent: sistema)
Category.create(name: 'Disponível para venda', parent: disponibilidade_sistema)
Category.create(name: 'Em desenvolvimento', parent: disponibilidade_sistema)

local_sistema = Category.create(name: 'Local de produção', parent: sistema)
Category.create(name: 'Brasil', parent: local_sistema)
Category.create(name: 'Fora do Brasil', parent: local_sistema)

