#coding: utf-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
#
#AdminUser.create!(:email => "test@test.com", :password => "testuser")

material = Category.create(name: 'Material')
classe = Category.create(name: 'Classe', parent: material)
Category.create!(name: 'Cerâmico/cimentício', parent: classe)
Category.create!(name: 'Compósito', parent: classe)
Category.create!(name: 'Couro', parent: classe)
Category.create!(name: 'Fibras naturais', parent: classe)
Category.create!(name: 'Florestal não-madeireiro', parent: classe)
Category.create!(name: 'Madeira', parent: classe)
Category.create!(name: 'Metal', parent: classe)
Category.create!(name: 'Papel e celulose', parent: classe)
Category.create!(name: 'Polímero', parent: classe)
Category.create!(name: 'Vidro', parent: classe)
sustentabilidade = Category.create(name: 'Sustentabilidade', parent: material)
agua = Category.create(name: 'Água', parent: sustentabilidade)
producao = Category.create(name: 'Produção', parent: agua)
Category.create!(name: 'Água1', parent: producao)
fonte = Category.create(name: 'Fonte', parent: agua)
Category.create!(name: 'Água2', parent: fonte)
uso = Category.create(name: 'Uso', parent: agua)
Category.create!(name: 'Água3', parent: uso)
ciclo = Category.create(name: 'Ciclo', parent: sustentabilidade)
Category.create!(name: 'Ciclo1', parent: ciclo)
Category.create!(name: 'Ciclo2', parent: ciclo)
Category.create!(name: 'Ciclo3', parent: ciclo)
seguranca = Category.create(name: 'Segurança', parent: sustentabilidade)
Category.create!(name: 'Segurança1', parent: seguranca)
Category.create!(name: 'Segurança2', parent: seguranca)
Category.create!(name: 'Segurança3', parent: seguranca)
humano_social =  Category.create(name: 'Humano/Social', parent: sustentabilidade)
Category.create!(name: 'Humano/Social 1', parent: humano_social)
energia =  Category.create(name: 'Energia', parent: sustentabilidade)
producao_energia = Category.create(name: 'Produção', parent: energia)
Category.create!(name: 'Produção 1', parent: producao_energia)
fonte_energia = Category.create(name: 'Fonte', parent: energia)
Category.create!(name: 'Fonte 1', parent: fonte_energia)
uso_energia = Category.create(name: 'Uso', parent: energia)
Category.create!(name: 'Uso 1', parent: uso_energia)
certificacao = Category.create(name: 'Certificação', parent: energia)
Category.create!(name: 'Certificação 1', parent: certificacao)
gestao = Category.create(name: 'Gestão', parent: sustentabilidade)
Category.create!(name: 'Gestão 1', parent: gestao)
uso = Category.create(name: 'Uso', parent: material)
Category.create!(name: 'Casa e construção', parent: uso)
Category.create!(name: 'Esporte e Lazer', parent: uso)
Category.create!(name: 'Moda', parent: uso)
caracteristicas = Category.create(name: 'Características', parent: material)
visuais = Category.create(name: 'Visuais', parent: caracteristicas)
Category.create!(name: 'Visuais 1', parent: visuais)
tateis = Category.create(name: 'Táteis', parent: caracteristicas)
Category.create!(name: 'Táteis 1', parent: tateis)
resistente = Category.create(name: 'Resistente à', parent: caracteristicas)
Category.create!(name: 'Resistente à 1', parent: resistente)
forma = Category.create(name: 'Forma', parent: caracteristicas)
Category.create!(name: 'Forma 1', parent: forma)
situacao = Category.create(name: 'Situação', parent: material)
Category.create!(name: 'Disponível para venda', parent: situacao)
Category.create!(name: 'Em desenvolvimento', parent: situacao)
local = Category.create(name: 'Local de produção', parent: material)
Category.create!(name: 'Acre', parent: local)
Category.create!(name: 'Alagoas', parent: local)
Category.create!(name: 'Amapá', parent: local)
Category.create!(name: 'Amazonas', parent: local)


produto = Category.create(name: 'Produto')
sustentabilidade = Category.create(name: 'Sustentabilidade', parent: produto)
agua = Category.create(name: 'Água', parent: sustentabilidade)
producao = Category.create(name: 'Produção', parent: agua)
Category.create!(name: 'Água1', parent: producao)
fonte = Category.create(name: 'Fonte', parent: agua)
Category.create!(name: 'Água2', parent: fonte)
uso = Category.create(name: 'Uso', parent: agua)
Category.create!(name: 'Água3', parent: uso)
ciclo = Category.create(name: 'Ciclo', parent: sustentabilidade)
Category.create!(name: 'Ciclo1', parent: ciclo)
Category.create!(name: 'Ciclo2', parent: ciclo)
Category.create!(name: 'Ciclo3', parent: ciclo)
seguranca = Category.create(name: 'Segurança', parent: sustentabilidade)
Category.create!(name: 'Segurança1', parent: seguranca)
Category.create!(name: 'Segurança2', parent: seguranca)
Category.create!(name: 'Segurança3', parent: seguranca)
humano_social =  Category.create(name: 'Humano/Social', parent: sustentabilidade)
Category.create!(name: 'Humano/Social 1', parent: humano_social)
energia =  Category.create(name: 'Energia', parent: sustentabilidade)
producao_energia = Category.create(name: 'Produção', parent: energia)
Category.create!(name: 'Produção 1', parent: producao_energia)
fonte_energia = Category.create(name: 'Fonte', parent: energia)
Category.create!(name: 'Fonte 1', parent: fonte_energia)
uso_energia = Category.create(name: 'Uso', parent: energia)
Category.create!(name: 'Uso 1', parent: uso_energia)
certificacao = Category.create(name: 'Certificação', parent: energia)
Category.create!(name: 'Certificação 1', parent: certificacao)
gestao = Category.create(name: 'Gestão', parent: sustentabilidade)
Category.create!(name: 'Gestão 1', parent: gestao)
uso = Category.create(name: 'Uso', parent: produto)
Category.create!(name: 'Casa e construção', parent: uso)
Category.create!(name: 'Esporte e Lazer', parent: uso)
Category.create!(name: 'Moda', parent: uso)
situacao = Category.create(name: 'Situação', parent: produto)
Category.create!(name: 'Disponível para venda', parent: situacao)
Category.create!(name: 'Em desenvolvimento', parent: situacao)
local = Category.create(name: 'Local de produção', parent: produto)
Category.create!(name: 'Acre', parent: local)
Category.create!(name: 'Alagoas', parent: local)
Category.create!(name: 'Amapá', parent: local)
Category.create!(name: 'Amazonas', parent: local)

sistema = Category.create(name: 'Sistema')
sustentabilidade = Category.create(name: 'Sustentabilidade', parent: sistema)
agua = Category.create(name: 'Água', parent: sustentabilidade)
producao = Category.create(name: 'Produção', parent: agua)
Category.create!(name: 'Água1', parent: producao)
fonte = Category.create(name: 'Fonte', parent: agua)
Category.create!(name: 'Água2', parent: fonte)
uso = Category.create(name: 'Uso', parent: agua)
Category.create!(name: 'Água3', parent: uso)
ciclo = Category.create(name: 'Ciclo', parent: sustentabilidade)
Category.create!(name: 'Ciclo1', parent: ciclo)
Category.create!(name: 'Ciclo2', parent: ciclo)
Category.create!(name: 'Ciclo3', parent: ciclo)
seguranca = Category.create(name: 'Segurança', parent: sustentabilidade)
Category.create!(name: 'Segurança1', parent: seguranca)
Category.create!(name: 'Segurança2', parent: seguranca)
Category.create!(name: 'Segurança3', parent: seguranca)
humano_social =  Category.create(name: 'Humano/Social', parent: sustentabilidade)
Category.create!(name: 'Humano/Social 1', parent: humano_social)
energia =  Category.create(name: 'Energia', parent: sustentabilidade)
producao_energia = Category.create(name: 'Produção', parent: energia)
Category.create!(name: 'Produção 1', parent: producao_energia)
fonte_energia = Category.create(name: 'Fonte', parent: energia)
Category.create!(name: 'Fonte 1', parent: fonte_energia)
uso_energia = Category.create(name: 'Uso', parent: energia)
Category.create!(name: 'Uso 1', parent: uso_energia)
certificacao = Category.create(name: 'Certificação', parent: energia)
Category.create!(name: 'Certificação 1', parent: certificacao)
gestao = Category.create(name: 'Gestão', parent: sustentabilidade)
Category.create!(name: 'Gestão 1', parent: gestao)
setor = Category.create(name: 'Setor', parent: sistema)
Category.create!(name: 'Setor 1', parent: setor)
situacao = Category.create(name: 'Situação', parent: sistema)
Category.create!(name: 'Disponível para venda', parent: situacao)
Category.create!(name: 'Em desenvolvimento', parent: situacao)
local = Category.create(name: 'Local de produção', parent: sistema)
Category.create!(name: 'Acre', parent: local)
Category.create!(name: 'Alagoas', parent: local)
Category.create!(name: 'Amapá', parent: local)
Category.create!(name: 'Amazonas', parent: local)
